Learning/DjangoTheoryPrac/PART1/newconcept/newconcept/urls.py
from django.contrib import admin
# include import here allows to connect urls from url.py files from 
# other applications in our project to our main project
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # add path for the homepage (base url)
    path('', views.homepage),
    # about page (2nd paramater is what view this url will show)
    path('about/', views.about),
    # from posts/url.py
    # this tells django we want to look inside our posts app and look at the urls file inside our posts
    # application that is created inside our project
    path('posts/', include('posts.urls'))
]
# static(): A helper function from django.conf.urls.static that serves static or media files during development.
# This line appends a route to the urlpatterns to allow the development server to serve media files uploaded by users.
# This setup is typically used only during development because Django's development server can serve files directly. In production, serving media files is handled by a web server (like Nginx or Apache) or a CDN.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Learning/DjangoTheoryPrac/PART1/newconcept/posts/urls.py
from django.urls import path
from . import views

# template folder is where you put html files. in settings.py you
# must let django know where this folder is to use ur html files.
# once you do it you have accsses to all template folders within your project
# that is why we dont have to do anything extra for posts app template folder
# by adding the name field we can now use the named URL when reffering to this adress(look in layout.html)

# once or project has more apps, its smart to add a namespace like below
# when linking html and url include name space exp:  <a href="{% url 'posts:page' slug=post.slug %}"> the name space would be posts here
app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    # we will use a path converter more specificly with slug
    # If the URL is /example-post, the slug variable will have the value 'example-post'.
    # slug (before :): Indicates that the segment should match the slug format.
    # slug (after :): The name of the variable passed to the view.
    # The slug path converter ensures that the dynamic segment of a URL only matches a valid slug pattern.
    path('<slug:slug>', views.post_page, name="page"),
    ]

# since this is url patterns from a app within our project 
# we need to register those urlpatterns in our main url.py file

Learning/DjangoTheoryPrac/PART1/newconcept/posts/models.py
from django.db import models
# models.py models ur data and each type of data will have a table in a db
# we use migration to take our python code here (our model) and turn it into tables in our database
# "py manage.py makemigrations" to make ur model migrations first (anytime a new model is added)
# "py manage.py migrate" to do migration 

# Create your models here.

# this is the post model or table
class Post(models.Model):
    # these are the fields in our model/table
    # this is the same as defining title as a VARCHAR with 75 char
    # these fields also relate to form inputs(how you accept the data for each field) which should be kept in mind
    title = models.CharField(max_length=75)
    body =  models.TextField()
    """  
    slug is what you would see at the end of the url  
    A URL-friendly string used to identify resources (e.g., blog posts, products).
    Contains only lowercase/uppercase letters, numbers, hyphens, or underscores.
    
    """
    slug = models.SlugField()
    # "auto_now_add=True" means a date time stamp will be added everytime a user adds another post
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    # we will define a method to return the title of the posts we save in our database
    # since this is not actually changing the data of the model we do not need to do another migration
    def __str__(self):
        return self.title

Learning/DjangoTheoryPrac/PART1/newconcept/newconcept/views.py
# http response was just to to make sure everything is connected
from django.http import HttpResponse
from django.shortcuts import render


# this would connect to the path("", ) code in urls since it is our homepage
# function will get request for the homepage 
def homepage(request):
    # return HttpResponse("hello!!! this is a simple HTTP response to a req for the homepage")
    # render will allow us to render our html files from template folder
    # pass render request and the html page you would like rendered
     return render(request,'home.html')
def about(request):
    # return HttpResponse("My About Page")
    return render(request,'about.html')

Learning/DjangoTheoryPrac/PART1/newconcept/posts/views.py
from django.shortcuts import render
from .models import Post

# since this is a new app we need to tell our django project in settings.py
# that we added a new app to the project


# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by("-date")
# even though django project can use all templates within ur project
# once there is more, except for the most global, you should add parent directory
# 3rd paramater is a Dictionary for the posts we have in our model.
    return render(request,'posts/posts_list.html', {"posts": posts})


def post_page(request, slug):
    # this will get the one post we have that matches the slug that was passed through
    post = Post.objects.get(slug=slug)
    return render(request,'posts/post_page.html', {"post": post})

Learning/DjangoTheoryPrac/PART1/newconcept/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content %}
    <section>
        <img 
            class="banner"
            src="{{ post.banner.url }}" 
            alt="{{ post.title }}"
        />
        <h1>{{post.title}}</h1>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>
    </section>
{% endblock %}

Learning/DjangoTheoryPrac/PART1/newconcept/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
<section>
    <h1>Posts</h1>
    {% for post in posts %}
    {% comment %} we use an article tag since we will have multiple posts {% endcomment %}
        <article class = "post">
            <h2>
                {% comment %} localhost:port/posts/first-post ('first-post' is the slug of the first post){% endcomment %}
                <a href="{% url 'posts:page' slug=post.slug %}">
                    {{post.title}}
                </a>
            </h2>
            <p>{{post.date}}</p>
            <p>{{post.body}}</p>
        </article>
    {% endfor %} 
</section>
{% endblock %}

Learning/DjangoTheoryPrac/PART1/newconcept/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

Learning/DjangoTheoryPrac/PART1/newconcept/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

Learning/DjangoTheoryPrac/PART1/newconcept/templates/layout.html
<!-- template folder is where you put html files. in settings.py you
 must let django know where this folder is to use ur html files. -->
<!-- adding our style sheets with django templateing engine
 {% load static %}
 <link rel="stylesheet" href="{% static 'css/style.css' %}" />
 -->

<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% comment %} block title here is default, will be replaced if other pages use a title {% endcomment %}
    <title> {% block title %} Django App {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">
        <span role="img" aria-label="Home">🏠</span>
      </a> | <a href="/about">
        <span role="img" aria-label="About">😀</span>
      </a> |
      {% comment %} (will use named URL instead) <a href="/posts">📰</a> {% endcomment %}
      {% comment %} using named url links instead of normal html links allows you to pass parameters and other layers of detail {% endcomment %}
      <a href="{% url 'posts:list' %}">
        <span role="img" aria-label="Posts">📰</span>
      </a>
    </nav>
    {% comment %} content can be added here later {% endcomment %}
    <main> {% block content %} {% endblock %} </main>
  </body>
</html>